server:
  port: 8080
  tomcat:
    max-connections: 10
    max-threads: 10
spring:
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#    配置初始化连接池大小，最小值，最大值
    initialSize: 5
    minIdle: 5
    maxActive: 20
#    配置获取数据库连接等待时间
    maxWait: 60000
#    配置多长时间进行一次检测，检测需要关闭的连接，单位是ms
    timeBetweenEvictionRunsMillis: 60000
#    配置连接在连接池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT *
    filters: stat,wall,slf4j
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.youngmanager.*.mapper.*,com.example.youngmanager.*.entity.*
logging:
  file: c:\youngmanager\log\yonugmanager.log
  level:
    com.example.youngmanager.common.mapper: debug
    com.example.youngmanager.common.controller: debug
pagehelper:
  helper-dialect: mysql
#  support-methods-arguments: true
#  reasonable: true
#  row-bounds-with-count: true


